### ISSUE TITLE
CalenarSync response: Call returned 400 (blank screen)?

### ISSUE THREAD

**Issue by HansS** [jasonjoh/node-calendar-sync#1]
can you give me a hint!

**Comment by jasonjoh** [comment]
I'd need to see the request and response. You could output the response body along with the response status code. Something like change this:

```
res.send('API Call returned ' + response.statusCode);
```

To this:

```
res.send('API Call returned ' + response.statusCode + '; BODY: ' + response.body);
```

**Comment by jasonjoh** [comment]
If you still have the issue please reopen with the requested info.
