### ISSUE TITLE
I have carried out steps you listed in your documentation, but getting an error message.

### ISSUE THREAD

**Issue by sanket-mindstix** [jasonjoh/node-calendar-sync#2]
While signing in I am getting an error message as 
**Cannot GET /sync**

Also while signings in, I am getting message as,
**Signed in as: undefined**

Thanks

**Comment by jasonjoh** [comment]
I just added the `profile` scope to the code so that Azure login will return the user's email address which should fix your "signed in as: undefined" issue.

**Comment by sanket-mindstix** [comment]
Great, thanks, issue has been fixed.
