### ISSUE TITLE
Login successful, no data

### ISSUE THREAD

**Issue by staminna** [jasonjoh/node-calendar-sync#3]
Hi Jason,

I can successfully login, but no errors or data is returned.
I have one email, onde calendar event and 1 contact on the account.
After I click sync, or refresh token then sync, always shows 

> Changes
Change type	Details	
-	No Changes
[]

I am using your latest commit from Fri Apr 15 10:12:22 2016

**Comment by jasonjoh** [comment]
It's likely due to the time window. The app syncs everything in the coming week (today to today + 7). If your event doesn't fall in that window, it won't come back. Try creating an event that falls in there or you can modify the window in the code:

```
// Set up our sync window from midnight on the current day to
// midnight 7 days from now.
var startDate = moment().startOf('day');
var endDate = moment(startDate).add(7, 'days');
```

**Comment by staminna** [comment]
Thanks. That was it

**Comment by staminna** [comment]
Why do the events disappear after refreshing the page? Hitting the sync bottom will also show zero events, even if they are on the date window

**Comment by jasonjoh** [comment]
Because it's a sync. After the initial "sync", you only get changes back.

**Comment by staminna** [comment]
Can it easily be made to look more like a standard mail box? thanks

**Comment by jasonjoh** [comment]
The look and behavior of the app is completely under your control. The point of this app was just as a rough example to show how sync works. This sample doesn't store anything anywhere, it just displays the results so you can see the sequence of events during sync. You could definitely sync to your own storage (database, local store, etc.) and display events/mail from that store to act more like a traditional mail client.
