### ISSUE TITLE
Sessions and cookies

### ISSUE THREAD

**Issue by staminna** [jasonjoh/node-calendar-sync#5]
I don't know if you are familiar with the MEAN.JS stack, but I am porting this functionality there though when I login to node-calendar-sync.

The first problem was both apps use express, but I wasn't able to make them run in the same port in parallel so I had to make the work in different ports using CORS.

I went around and I worked for two weeks trying to http.get data from Express routes to Angular and I made it but it doesn't work for routes that need authentication.

MEAN.JS also uses express-session and passport for Oauth2.

Can you help with a perhaps a link or some pointers? I very new to these technologies. 
Thanks!

**Comment by jasonjoh** [comment]
No sorry, I'm not familiar.
