### ISSUE TITLE
ERROR getting token

### ISSUE THREAD

**Issue by staminna** [jasonjoh/node-calendar-sync#6]
Hi Jason,

I have seen this error before, but now even after creating new token in apps.dev.microsoft.com I'm not seeing how to fix this as there isn't anything on the browser console.

There is another (quick) question: Is it possible to fetch tasks with node-calendar-sync? 
I will perhaps close the initial issue about the contacts and restart from scratch.

**Comment by jasonjoh** [comment]
Which error are you referring to?

You can get tasks via the REST APIs, but this sample has nothing to do with them. https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/outlooktask

**Comment by staminna** [comment]
ERROR getting token: [object Object]
after I insert the password to login.

**Comment by jasonjoh** [comment]
Need to expand that object there. Try replacing

```
console.log('ERROR getting token:'  + error);
```

with

```
console.log('ERROR getting token:'  + JSON.stringify(error));
```

**Comment by staminna** [comment]
I had the production environment setup on development machine.
Btw, how can I have both redirectURI available for production and development environment in the same code? Now I remember I always need to use nano on production to edit the authHelper.js after I push the code to the server?

**Comment by jasonjoh** [comment]
So much of that depends on your code and setup. But generally the answer is don't hard-code the redirect URI in your code, derive it at runtime based on the environment.
